-- MySQL Script generated by MySQL Workbench
-- Fri Oct 22 22:20:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema social_media
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema social_media
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social_media` DEFAULT CHARACTER SET utf8;
USE `social_media`;

-- -----------------------------------------------------
-- Table `social_media`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_media`.`User`
(
    `uid`            INT          NOT NULL AUTO_INCREMENT,
    `email`          VARCHAR(120) NOT NULL,
    `username`       VARCHAR(80)  NOT NULL DEFAULT 'username',
    `name`           VARCHAR(45)  NULL,
    `user_image_url` VARCHAR(300) NULL,
    `token`            VARCHAR(3000) NULL,
    `bio`            VARCHAR(300) NULL,
    `phone_number`   VARCHAR(45)  NULL,
    `password`       VARCHAR(60)  NOT NULL,
    PRIMARY KEY (`uid`, `email`, `username`)
)
    ENGINE = InnoDB;

ALTER TABLE User AUTO_INCREMENT = 200401;

-- -----------------------------------------------------
-- Table `social_media`.`SocialConnection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_media`.`SocialConnection`
(
    `uid`               INT          NOT NULL,
    `social_type`       VARCHAR(60)  NULL,
    `user_profile_link` VARCHAR(500) NULL,
    INDEX `social_user_idx` (`uid` ASC) VISIBLE,
    CONSTRAINT `social_user`
        FOREIGN KEY (`uid`)
            REFERENCES `social_media`.`User` (`uid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_media`.`Post`
(
    `pid`     INT          NOT NULL DEFAULT 1,
    `caption` VARCHAR(320) NULL,
    `uid`     VARCHAR(45)  NOT NULL,
    `time`    TIMESTAMP    NULL,
    PRIMARY KEY (`pid`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_media`.`Like`
(
    `uid`  INT       NOT NULL,
    `time` TIMESTAMP NULL,
    `pid`  INT       NOT NULL,
    INDEX `like_user_idx` (`uid` ASC) VISIBLE,
    INDEX `like_post_idx` (`pid` ASC) VISIBLE,
    CONSTRAINT `like_user`
        FOREIGN KEY (`uid`)
            REFERENCES `social_media`.`User` (`uid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `like_post`
        FOREIGN KEY (`pid`)
            REFERENCES `social_media`.`Post` (`pid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_media`.`Comment`
(
    `pid`             INT          NOT NULL,
    `uid`             INT          NOT NULL,
    `comment_content` VARCHAR(120) NULL,
    `time`            TIMESTAMP    NULL,
    INDEX `uid_idx` (`uid` ASC) VISIBLE,
    INDEX `comment_post_idx` (`pid` ASC) VISIBLE,
    CONSTRAINT `comment_user`
        FOREIGN KEY (`uid`)
            REFERENCES `social_media`.`User` (`uid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `comment_post`
        FOREIGN KEY (`pid`)
            REFERENCES `social_media`.`Post` (`pid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`Share`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_media`.`Share`
(
    `uid`     INT         NOT NULL,
    `pid`     INT         NOT NULL,
    `time`    TIMESTAMP   NULL,
    `caption` VARCHAR(45) NULL,
    INDEX `share_post_idx` (`pid` ASC) VISIBLE,
    INDEX `share_user_idx` (`uid` ASC) VISIBLE,
    CONSTRAINT `share_post`
        FOREIGN KEY (`pid`)
            REFERENCES `social_media`.`Post` (`pid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `share_user`
        FOREIGN KEY (`uid`)
            REFERENCES `social_media`.`User` (`uid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`Connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_media`.`Connection`
(
    `c_1_uid` INT       NOT NULL,
    `c_2_uid` INT       NOT NULL,
    `time`    TIMESTAMP NULL,
    INDEX `connection_1_user_idx` (`c_1_uid` ASC) VISIBLE,
    INDEX `connection_2_user_idx` (`c_2_uid` ASC) VISIBLE,
    CONSTRAINT `connection_1_user`
        FOREIGN KEY (`c_1_uid`)
            REFERENCES `social_media`.`User` (`uid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `connection_2_user`
        FOREIGN KEY (`c_2_uid`)
            REFERENCES `social_media`.`User` (`uid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`ConnectionRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_media`.`ConnectionRequest`
(
    `request_from_uid` INT       NOT NULL,
    `request_to_uid`   INT       NOT NULL,
    `request_time`     TIMESTAMP NULL,
    INDEX `connection_request_user_idx` (`request_from_uid` ASC) VISIBLE,
    INDEX `connection_request_to_user_idx` (`request_to_uid` ASC) VISIBLE,
    CONSTRAINT `connection_request_from_user`
        FOREIGN KEY (`request_from_uid`)
            REFERENCES `social_media`.`User` (`uid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `connection_request_to_user`
        FOREIGN KEY (`request_to_uid`)
            REFERENCES `social_media`.`User` (`uid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`Notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_media`.`Notifications`
(
    `uid`     INT          NOT NULL,
    `n_type`  VARCHAR(60)  NULL,
    `message` VARCHAR(200) NULL,
    INDEX `notification_user_idx` (`uid` ASC) VISIBLE,
    CONSTRAINT `notification_user`
        FOREIGN KEY (`uid`)
            REFERENCES `social_media`.`User` (`uid`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_media`.`Socia_lUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_media`.`Socia_lUser`
(
    `uid`            INT          NOT NULL AUTO_INCREMENT,
    `username`       VARCHAR(80)  NOT NULL DEFAULT 'username',
    `name`           VARCHAR(45)  NULL,
    `user_image_url` VARCHAR(300) NULL,
    `bio`            VARCHAR(300) NULL,
    `email`          VARCHAR(120) NULL,
    `phone_number`   VARCHAR(45)  NULL,
    `token`          VARCHAR(400) NULL,
    PRIMARY KEY (`uid`, `username`)
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
